

### root
GET http://localhost:3000/


### user_register
POST http://localhost:3000/user/register 
Content-Type: application/json

{"email": "john@doe.com", "password": "ChangeMe1234#"}


### auth_login
# @name auth_login
POST http://localhost:3000/auth/login 
Content-Type: application/json

{"email": "john@doe.com", "password": "changeme"}

###
@access_token = {{auth_login.response.body.access_token}}



### auth_info
GET http://localhost:3000/auth/info 
Authorization: Bearer {{access_token}}


### todos_list
GET http://localhost:3000/todos
Authorization: Bearer {{access_token}}

### todos_add
POST http://localhost:3000/todos
Authorization: Bearer {{access_token}}
Content-Type: application/json

{"content": "My todo item"}
